// This is the root layout of the project. Its not optional.

// Every react component needs a children prop. This is where your page content will go
// Page.tsx becomes the child of layout.tsx when layout is rendered

// Children prop is all of your components in the app folder.

import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    template: "%s | Next Learning", // works when you need to add prefixes and suffixes to all
    // of your titles. %s is your original title
    default: "Next.js Course", // Works for any child components that don't specify their
    // title value
    absolute: "Exception", // Add it as a property to component's metadata, and its name will
    // be excluded from the templates above, meaning you can set a custom name
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>Header</p>
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
// You can modify the elements in the layout. These elements will appear on every page
// Useful for headers and footers
// Better to make separate components for Header and Footer
